### PR TITLE
M5 calculator Completed

### PR DESCRIPTION
**Pull request by Aaron-RN**
Tied in the operate and calculate logic modules with the app component.
- Features
- [x] - Basic calculator with +, -, x, ÷ and % arithmetic logic.
- [x] - Also has A/C, 'Clear All' button
- [x] - Numbers 0 -9 with decimal acceptance
- [x] - Allows for multiple calculations without the need to use the '=' button
- [x] - Has a calculation history that also displays within the main display of the calculator

### CODE REVIEW

**Review by Oghenebrume50 — CHANGES_REQUESTED** [review]
### STATUS: CHANGES REQUIRED 

Hi @Aaron-RN good job working on this, the UI looks great and the basic functionalities are working too :+1: but I would like to point the things that aren't working yet. 

- There is a need for continuation with previous calculated value, example( 9 + 5 = 14) pressing on + immediately after this should do 14 + (the next number) but this doesn't happen on your app please look into that. 

- The % operator should return num / 100 as  it's output

Please make changes and request for another review :slightly_smiling_face: 

**RAPHAEL NORIODE** :world_map:

**Comment by Aaron-RN** [comment]
> ### STATUS: CHANGES REQUIRED
> Hi @Aaron-RN good job working on this, the UI looks great and the basic functionalities are working too 👍 but I would like to point the things that aren't working yet.
> 
> * There is a need for continuation with previous calculated value, example( 9 + 5 = 14) pressing on + immediately after this should do 14 + (the next number) but this doesn't happen on your app please look into that.
> * The % operator should return num / 100 as  it's output
> 
> Please make changes and request for another review 🙂
> 
> **RAPHAEL NORIODE** 🗺️

Sorry I don't quite understand what you mean regarding the % modulus operator returning num / 100 as output?

You are saying the modulus operator should be calculated by using num / 100?
I just used the .mod() function provided by Big.js...

**Review by shloch — CHANGES_REQUESTED** [review]
## hello @Aaron-RN 
Nice with the first remark........
Screen Shot 2020-04-11 at 5 02 04 PM

The display is phenomenal

### [required changes]

However you have not changed the second small observation. It's not the `modulo` operator this time. i see the confusion. It's the  inverse`PERCENTAGE` operator (i.e DIVISION BY 100). Thats why former TSE said `number/100`

if i press `8`, then i press `%`, i should have as result = `0.08`

### that's last small thing to do

**Comment by Aaron-RN** [comment]
> ## hello @Aaron-RN
> Nice with the first remark........
> Screen Shot 2020-04-11 at 5 02 04 PM
> 
> The display is phenomenal
> 
> ### [required changes]
> However you have not changed the second small observation. It's not the `modulo` operator this time. i see the confusion. It's the inverse`PERCENTAGE` operator (i.e DIVISION BY 100). Thats why former TSE said `number/100`
> 
> if i press `8`, then i press `%`, i should have as result = `0.08`
> 
> ### that's last small thing to do

Ahhhhhhh, Okay gotcha!

**Review by Oghenebrume50 — CHANGES_REQUESTED** [review]
### STATUS: APPROVED 

Hi @Aaron-RN good job working on this, it is coming along very well, there is just one small thing to do now,  if I make a calculation,  say 9 + 5 I get 14, if I then press the number 6, I want to see just 6, but currently what happens is that 6 is appended to 14 to become 146, please look into that :slightly_smiling_face: 

Also, my apologies for not answering your questions earlier, it is generally better to reach out to me on Slack GitHub notifications can get clumsy. 

Please make changes and request for another review :slightly_smiling_face: 

**RAPHAEL NORIODE** :world_map:

**Comment by MauricioRobayo** [comment]
This is it. Thanks for taking care of the last issue from the previous review.

Please move on, you are almost there!

Status: __Approved__.

**Review by MauricioRobayo — APPROVED** [review]
This is it. Thanks for taking care of the last issue from the previous review.

Please move on, you are almost there!

Status: __Approved__.

**Pull request merged**
